# Welcome to Jekyll!

# Website settings
title: Bahtiyar Gursoy
description: BI Developer / Data Engineer / Lifelong Learner # / New Father
keywords: Developer,BI Developer,Data Engineer,Lifelong Learner,Basketballer,blog,Jekyll,github,gh-pages,Microstrategy,Oracle
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://wwww.bahtiyarg.com  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Bahtiyar Gursoy  # Be used at blog posts' author.
  first_name: Bahtiyar  # Be used at index page about me section.
  last_name: Gursoy  # Be used at index page about me section.
  avatar: /static/assets/img/landing/Bahti.jpg #bahti.jpg  # upload your avatar at directory and edit it.
  github_username: bahtiyarg  # Leave blank if you don't have now
  linkedin_id: bahtiyarg # Leave blank if you don't have now
  twitter_username: bahtiyarg  # Leave blank if you don't have now
#  facebook_username: bahtiyarg  # Leave blank if you don't have now
  email: me@bahtiyarg.com  # Leave blank if you don't have now
  cv: http://www.bahtiyarg.com/resume.pdf  # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-database
    - name: fa-table #fa-tachometer
  skill_icon2:
    - name: fa-tachometer #icon-python
    - name: icon-java-bold #icon-aws
  desc: BI Developer / Data Engineer / Lifelong Learner # / New Father  # Describe yourself.

# comment
#disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  #name: bahtiyarg
  #public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
   id: UA-91642671-1

## growingIO
#gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge